"""Read-only source-view materialization and verification contract.

The provider adapter consumes only the marker constants from this module; it
does not own filesystem mirroring policy.
"""

from __future__ import annotations

import errno
import json
import os
import shutil
import sys
import uuid
from pathlib import Path

from app.gateway.bug_runtime_source_policy import (
    directory_is_required_for_runtime_dist,
    discover_tracked_runtime_dist_roots,
    git_tracked_files,
    path_is_in_runtime_dist,
)

try:
    import fcntl
except ImportError:  # pragma: no cover - Windows
    fcntl = None  # type: ignore[assignment]
    import msvcrt

SOURCE_VIEW_POLICY = "deerflow-source-only-v4"
SOURCE_VIEW_MARKER = ".deerflow-source-view.json"
SOURCE_QUERY_RUNTIME = ".deerflow-source-query.py"
SOURCE_QUERY_LAUNCHER = ".deerflow-source-query-runner.py"
LOG_QUERY_RUNTIME = ".deerflow-log-query.py"
LOG_CACHE_DIRECTORY = ".deerflow-runtime-evidence"
SOURCE_VIEW_EXCLUDED_DIRECTORIES = frozenset(
    {
        ".git",
        ".gradle",
        ".next",
        ".nuxt",
        ".output",
        ".turbo",
        ".cxx",
        ".claude",
        ".cursor",
        LOG_CACHE_DIRECTORY,
        "build",
        "deriveddata",
        "dist",
        "intermediates",
        "memory-bank",
        "node_modules",
        "out",
        "target",
    }
)
SOURCE_VIEW_EXCLUDED_FILENAMES = frozenset(
    {
        ".cursorrules",
    }
)
SOURCE_VIEW_EXCLUDED_SUFFIXES = frozenset(
    {
        ".7z",
        ".aab",
        ".apk",
        ".bundle",
        ".bz2",
        ".gz",
        ".ipa",
        ".jar",
        ".jsbundle",
        ".rar",
        ".tar",
        ".tgz",
        ".war",
        ".xcarchive",
        ".xz",
        ".zip",
    }
)


def _source_view_marker(repository_name: str) -> bytes:
    return (
        json.dumps(
            {"policy": SOURCE_VIEW_POLICY, "repository": repository_name, "schema_version": 4},
            ensure_ascii=False,
            sort_keys=True,
            separators=(",", ":"),
        )
        + "\n"
    ).encode()


def _source_query_launcher() -> bytes:
    """Bind the in-view query to Gateway's bounded structural parser."""
    # Preserve the venv executable path: resolving its symlink loses the venv.
    python = str(Path(sys.executable).absolute())
    return (
        "# Source-only Bug relation query; generated by DeerFlow.\n"
        "import subprocess\nimport sys\nfrom pathlib import Path\n\n"
        f"python = {python!r}\n"
        f"query = Path(__file__).with_name({SOURCE_QUERY_RUNTIME!r})\n"
        "raise SystemExit(subprocess.call([python, str(query), *sys.argv[1:]]))\n"
    ).encode()


def _source_view_file_allowed(
    relative_path: Path,
    *,
    tracked_files: frozenset[Path],
    runtime_dist_roots: frozenset[Path],
) -> bool:
    excluded_parts = {part.lower() for part in relative_path.parts} & SOURCE_VIEW_EXCLUDED_DIRECTORIES
    if excluded_parts and not (
        excluded_parts == {"dist"}
        and relative_path in tracked_files
        and path_is_in_runtime_dist(relative_path, runtime_dist_roots)
    ):
        return False
    lower_name = relative_path.name.lower()
    if lower_name in SOURCE_VIEW_EXCLUDED_FILENAMES:
        return False
    return not any(lower_name.endswith(suffix) for suffix in SOURCE_VIEW_EXCLUDED_SUFFIXES)


def materialize_bug_source_view(source_root: Path, view_root: Path, *, repository_name: str) -> None:
    """Reconcile a source-only Bug investigation view without history or builds."""
    source_root = source_root.expanduser().resolve(strict=True)
    view_root = view_root.expanduser().resolve(strict=False)
    if not source_root.is_dir():
        raise ValueError(f"Bug source root is not a directory: {source_root}")
    if view_root == source_root or source_root in view_root.parents or view_root in source_root.parents:
        raise ValueError("Bug source view must be outside the source repository")
    if not repository_name or Path(repository_name).name != repository_name:
        raise ValueError(f"Invalid Bug source-view repository name: {repository_name!r}")

    view_root.parent.mkdir(parents=True, exist_ok=True)
    lock_path = view_root.parent / f".{repository_name}.source-view.lock"
    with lock_path.open("a+b") as lock_file:
        if fcntl is not None:
            fcntl.flock(lock_file.fileno(), fcntl.LOCK_EX)
        else:  # pragma: no cover - Windows
            lock_file.seek(0)
            lock_file.write(b"\0")
            lock_file.flush()
            lock_file.seek(0)
            msvcrt.locking(lock_file.fileno(), msvcrt.LK_LOCK, 1)
        view_root.mkdir(parents=True, exist_ok=True)
        desired_files: set[Path] = set()
        tracked_files = git_tracked_files(source_root)
        runtime_dist_roots = discover_tracked_runtime_dist_roots(source_root, tracked_files=tracked_files)

        for current_root, directory_names, file_names in os.walk(source_root, followlinks=False):
            current = Path(current_root)
            relative_directory = current.relative_to(source_root)
            directory_names[:] = [
                name
                for name in directory_names
                if not (current / name).is_symlink()
                and (
                    name.lower() not in SOURCE_VIEW_EXCLUDED_DIRECTORIES
                    or (
                        name.lower() == "dist"
                        and directory_is_required_for_runtime_dist(relative_directory / name, runtime_dist_roots)
                    )
                )
            ]
            target_directory = view_root / relative_directory
            target_directory.mkdir(parents=True, exist_ok=True)
            for file_name in file_names:
                source_file = current / file_name
                relative_file = relative_directory / file_name
                if source_file.is_symlink() or not _source_view_file_allowed(
                    relative_file,
                    tracked_files=tracked_files,
                    runtime_dist_roots=runtime_dist_roots,
                ):
                    continue
                desired_files.add(relative_file)
                target_file = view_root / relative_file
                target_file.parent.mkdir(parents=True, exist_ok=True)
                try:
                    if target_file.exists() and os.path.samefile(source_file, target_file):
                        continue
                except OSError:
                    pass
                temporary = target_file.with_name(f".{target_file.name}.{uuid.uuid4().hex}.tmp")
                try:
                    try:
                        os.link(source_file, temporary)
                    except OSError as exc:
                        if exc.errno not in {errno.EXDEV, errno.EPERM, errno.EACCES, errno.EMLINK}:
                            raise
                        shutil.copy2(source_file, temporary)
                    os.replace(temporary, target_file)
                finally:
                    temporary.unlink(missing_ok=True)

        marker_relative = Path(SOURCE_VIEW_MARKER)
        desired_files.add(marker_relative)
        marker_path = view_root / marker_relative
        marker_bytes = _source_view_marker(repository_name)
        if not marker_path.is_file() or marker_path.read_bytes() != marker_bytes:
            marker_temporary = marker_path.with_name(f".{marker_path.name}.{uuid.uuid4().hex}.tmp")
            marker_temporary.write_bytes(marker_bytes)
            os.replace(marker_temporary, marker_path)

        for runtime_name, runtime_module in ((SOURCE_QUERY_RUNTIME, "bug_source_query_runtime.py"), (LOG_QUERY_RUNTIME, "bug_log_query_runtime.py")):
            runtime_relative = Path(runtime_name)
            desired_files.add(runtime_relative)
            runtime_path = view_root / runtime_relative
            runtime_bytes = Path(__file__).with_name(runtime_module).read_bytes()
            if not runtime_path.is_file() or runtime_path.read_bytes() != runtime_bytes:
                runtime_temporary = runtime_path.with_name(f".{runtime_path.name}.{uuid.uuid4().hex}.tmp")
                runtime_temporary.write_bytes(runtime_bytes)
                os.replace(runtime_temporary, runtime_path)

        launcher_relative = Path(SOURCE_QUERY_LAUNCHER)
        desired_files.add(launcher_relative)
        launcher_path = view_root / launcher_relative
        launcher_bytes = _source_query_launcher()
        if not launcher_path.is_file() or launcher_path.read_bytes() != launcher_bytes:
            launcher_temporary = launcher_path.with_name(f".{launcher_path.name}.{uuid.uuid4().hex}.tmp")
            launcher_temporary.write_bytes(launcher_bytes)
            os.replace(launcher_temporary, launcher_path)

        for current_root, directory_names, file_names in os.walk(view_root, topdown=False, followlinks=False):
            current = Path(current_root)
            # Per-run runtime evidence is not mirrored source. Concurrent
            # investigations must not erase each other's private indices.
            if LOG_CACHE_DIRECTORY in current.relative_to(view_root).parts:
                continue
            for file_name in file_names:
                candidate = current / file_name
                if candidate.relative_to(view_root) not in desired_files:
                    candidate.unlink(missing_ok=True)
            for directory_name in directory_names:
                candidate = current / directory_name
                if candidate.is_symlink():
                    candidate.unlink(missing_ok=True)
                else:
                    try:
                        candidate.rmdir()
                    except OSError:
                        pass
